import type { Metadata } from "next";
import {
    Arsenal as font_sans,
    Arsenal_SC as font_mono,
    Zen_Dots as font_special,
} from "next/font/google";
import "./globals.css";
import { Suspense } from "react";
import { Toaster } from "sonner";

const fontSans = font_sans({
    variable: "--font-font-sans",
    subsets: ["latin"],
    weight: "400",
});

const fontMono = font_mono({
    variable: "--font-font-mono",
    subsets: ["latin"],
    weight: "400",
});

const fontSpecial = font_special({
    variable: "--font-font-special",
    subsets: ["latin"],
    weight: "400",
});

export const metadata: Metadata = {
    title: "M I S T 2.0",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${fontSans.variable} ${fontMono.variable} ${fontSpecial.variable} antialiased background`}
            >
                <Suspense>{children}</Suspense>
                <Toaster position="top-center" />
            </body>
        </html>
    );
}
